spring.application.name=weather-outfit-assistant

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/weather_assistant
spring.datasource.username=root
spring.datasource.password=Kaneki#G1317

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
